[tool.towncrier]
    version = "NEW_VERSION"
    directory = "changelog.d"
    filename = "TCHAP_CHANGES.md"
    name = "Changes in Tchap"
    template = "tools/towncrier/template.md"
    issue_format = "[#{issue}](https://github.com/tchapgouv/tchap-android-v2/issues)"

    [[tool.towncrier.type]]
        directory = "feature"
        name = "Features ‚ú®"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bugfixes üêõ"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "doc"
        name = "Improved Documentation üìö"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "removal"
        name = "SDK API changes ‚ö†Ô∏è"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "misc"
        name = "Other changes"
        showcontent = true
